# Generated by Django 2.2.6 on 2019-11-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginvalue',
            name='iin',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='loginvalue',
            name='phone_number',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
    ]
