# Generated by Django 2.2.6 on 2019-11-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0002_auto_20191117_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginvalue',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='loginvalue',
            name='surname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
