# Generated by Django 2.2.6 on 2019-12-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0003_auto_20191117_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='cvv',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
